version: '2.4'
services:


  #  robot_zookeeper:
  #    extends:
  #      file: kafka.docker-compose.yml
  #      service: zookeeper
  #
  #  robot_broker:
  #    extends:
  #      file: kafka.docker-compose.yml
  #      service: broker
  #    ports:
  #      - '9031:9031'
  #    environment:
  #      - KAFKA_CFG_LISTENERS=CLIENT://:29000,EXTERNAL://:9031
  #      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker:29000,EXTERNAL://localhost:9031
  #    depends_on:
  #      - robot_zookeeper
  #
  #  robot_kafka_ui:
  #    extends:
  #      file: kafka.docker-compose.yml
  #      service: kafka-ui
  #    depends_on:
  #      - 'robot_broker'
  #    ports:
  #      - '9021:8080'

  zookeeper:
    image: 'bitnami/zookeeper:latest'
    hostname: zookeeper
    #    ports:
    #      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  broker:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    hostname: broker
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=CLIENT
      - KAFKA_CFG_LISTENERS=CLIENT://:29000,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=CLIENT://broker:29000,EXTERNAL://localhost:9092
    depends_on:
      - zookeeper
    healthcheck:
      test: /opt/bitnami/kafka/bin/kafka-topics.sh --bootstrap-server localhost:29000 --list
      interval: 2s
      start_period: 10s
      timeout: 15s
      retries: 100

  kafka-ui:
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '8080:8080'
    depends_on:
      - broker
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=broker:29000
