version: '3.8'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "9031:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29000,PLAINTEXT_HOST://localhost:9031
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29000'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  monitor:
    image: delivery-monitor:latest
    depends_on:
      - broker
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  comms:
    image: delivery-communication:latest
    depends_on:
      - monitor
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'
      MESSAGES: 'ccu.DeliveryStatusRequest,ccu.NewTaskRequest'
      SERVER_URI: '172.17.0.1:9010'

  hmi:
    image: delivery-hmi:latest
    ports:
      - "9041:8888"
    depends_on:
      - monitor
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  motion:
    image: delivery-motion:latest
    depends_on:
      - monitor
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  odom:
    image: delivery-odometer:latest
    depends_on:
      - monitor
      - motion
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  location:
    image: delivery-location:latest
    depends_on:
      - monitor
      - odom
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'
      SPEED_TAMPERED_TRIGGER: 5
      DISTANCE_TAMPERED_TRIGGER: 50
      UPDATE_INTERVAL_SEC: 10
      SERVICES: 'odom'

  sensors:
    image: delivery-sensors:latest
    depends_on:
      - monitor
      - location
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  locker:
    image: delivery-locker:latest
    depends_on:
      - monitor
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'

  central:
    image: delivery-central:latest
    restart: always
    depends_on:
      - monitor
      - comms
      - motion
      - location
      - sensors
      - locker
    volumes:
      - ./certs/secret_keystore.p12:/app/secret_keystore.p12:ro
      - ./certs/client_sign_keystore.p12:/app/client_sign_keystore.p12:ro
    environment:
      KAFKA_BOOTSTRAP_SERVER: 'broker:29000'
      AES_KS_PATH: '/app/secret_keystore.p12'
      AES_KS_PASS: 'kiuw2ka7ahSeeTh2wieb6ohy1Xu3haj4'
      SIGN_KS_PATH: '/app/client_sign_keystore.p12'
      SIGN_KS_PASS: 'uogh7noh4Ree8huZ9shae7vi6ohphohj'
